# This workflow will publish releases to https://pypi.org/project/lagrange-rmatrix/

name: Pypi publish

on:
  release:
    types: [published]
  
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/lagrange-rmatrix/
    permissions:
      id-token: write  
    steps:
    - name: Install package and dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install twine build
    - name: Build wheel and sdist
      run: |
        python3 -m build --sdist --wheel 
        
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
