# This workflow will publish releases to https://pypi.org/project/lagrange-rmatrix/

name: Pypi publish

on:
  release:
    types: [published]
  
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/lagrange-rmatrix/
    permissions:
      id-token: write  
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
